### ISSUE TITLE
Auto modes (fan & heat-cool)

### ISSUE THREAD

**Issue by herbi3** [yenoiwesa/homebridge-daikin-airbase#45]
Is there a way to support auto cooling & heating? along with auto fan speed mode.

Currently I can only access heat, cool & off + adjusting the fan speeds off, 33% etc but no auto function.

The only way I can use auto fan speed is my adjusting it via the airbase app or on the controller itself manually.

if I manually send the command to the airbase unit using "f_rate=0" it sets the fan to auto speed with cooling
(http://10.0.2.32/skyfi/aircon/set_control_info?lpw=&mode=2&f_airside=0&dt2=24.0&f_rate=0&shum=0&pow=1&stemp=21.0&f_dir=0&f_auto=0)

I can set auto cool/heat mode by using "mode=3" my example below doesn't include the auto range temperature
(http://10.0.2.32/skyfi/aircon/set_control_info?lpw=&mode=3&f_airside=0&dt2=24.0&f_rate=0&shum=0&pow=1&stemp=21.0&f_dir=0&f_auto=0)

**Comment by herbi3** [comment]
this is the occasional error within homebridge

"This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics"

**Comment by yenoiwesa** [comment]
Hi there @herbi3 👋 

Regarding the auto fan mode, the Daikin Airbase supports it but a fan accessory cannot be set as auto in the Home app, there is no option for that state in HomeKit and thus in the Home app UI. So this is a case where I had to not support it because it couldn't be mapped to the HomeKit API (or at least not in a way that I found acceptable).

Regarding the support of auto climate mode, this is already supported by the plug-in but only if I receive the flag that says it is supported. The Daikin Airbase returns that support flag as false for my aircon despite the wall controller supporting auto mode just fine. I contacted Daikin support about it and they just told me that the Daikin Airbase is not compatible with controlling auto mode for my aircon model 🤷

I tried to do what you suggest and send the value for auto mode either way, but that puts the aircon in a strange mode where next commands are not executed properly (I don't remember the details but I remember that it was broken enough to not support).

Hope that answers your questions.

**Comment by herbi3** [comment]
thanks @yenoiwesa!

Makes sense for the fan option, bit of a shame HomeKit doesn't support a fourth option. I am hoping to modify it and make the 100% setting in HomeKit to send the auto fan speed option

bugger for the auto cool/heat mode - my ducted system supports auto heat/cool just as long as mode is set to "=3" and then with the range temperature flags too. my example wasn't the greatest, just the quickest I produced at the time.

thanks again @yenoiwesa !

**Comment by yenoiwesa** [comment]
@herbi3 if you feel like trying it, you could add support for a new override option in the plugin settings to override the auto mode support received from the Airbase. If you manage to get the auto mode working I am super interested myself hehe.

**Comment by herbi3** [comment]
@yenoiwesa I have no idea how to implement the override values within the config, just for testing I tried to disable dry mode  but it still shows as active in the logs etc.

the device itself may not have an auto function completely (between all settings), however they may have a keep between value for heat & cool.

Is it possible to have this push to HomeKit regardless of response from "en_auto" ?

if (accessory.context.airbase.autoModeSupported) {
            validTargetHeaterCoolerStates.push(
                Characteristic.TargetHeaterCoolerState.AUTO
            );

        }

**Comment by yenoiwesa** [comment]
I will close this issue as I do not intend to implement an override for the auto mode support.
