### ISSUE TITLE
Automate using homebridge-daikin-airbase

### ISSUE THREAD

**Issue by keertisomu** [yenoiwesa/homebridge-daikin-airbase#54]
Hi,

I've successfully setup and I am able to control my aircon (BRP15B61) using homebridge & homebridge-daikin-airbase module (thanks for the module by the way :-) ). I would like to automate with some rules like turn on the aircon at early hours at around 3.00 AM (just an example). 
Basically do some timebase or temperature automation.
Any advice on how can i go about it.

Thanks,
Keerti.

**Comment by yenoiwesa** [comment]
Hey there,

Since you have setup this Daikin Airbase Homebridge plugin, you should see your aircon in the Apple Home app on your Apple devices. Then, in the Home app, you can just navigate to the automation tab and setup an automation.

For instance, I myself have one to turn on the aircon to 23 degrees at 6.50am every day:
<img width="598" alt="image" src="https://github.com/yenoiwesa/homebridge-daikin-airbase/assets/1464666/bad1af6b-2651-45a1-ac0e-46f78635b3a1">

Note that to have Apple Home automations, you must have an Apple TV or an Apple HomePod in your home.

Hope that helps.

**Comment by keertisomu** [comment]
Hi,
Thanks for your reply. Makes sense now.
I don't have either of them :) so its time to buy either of them. 
Again , thanks this was really helpful.
